kind: Service
apiVersion: v1
metadata:
  name: persona
  namespace: {{ .Values.namespace }}
  labels:
    app: persona
    app.kubernetes.io/name: {{ .Values.app.kubernetes.io.name }}
    app.kubernetes.io/version: v1
    version: v1
  annotations:
    kubesphere.io/serviceType: statelessservice
    servicemesh.kubesphere.io/enabled: 'false'
spec:
  ports:
    - name: http-web
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app: persona
    app.kubernetes.io/version: v1
  type: {{ .Values.service.type }}
  sessionAffinity: None
