kind: ConfigMap
apiVersion: v1
metadata:
  name: qxp-web-home-config
  namespace: {{ .Values.namespace }}
  annotations:
    kubesphere.io/alias-name: qxp-web-home-config

data:
  config.yaml: |-
    dev_mode: false

    api_endpoint:
      protocol: http
      hostname: polygate
      port: 80

    http_client:
      timeout: 30
      max_conn: 100
      dial_timeout: 30
      idle_conn_timeout: 90

    redis:
      {{- with .Values.config.redis.addrs }}
      addrs:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      username: {{ .Values.config.redis.username }}
      password: {{ .Values.config.redis.password }}
      timeout: {{ .Values.config.redis.timeout }}

    portal_server:
      server_port: 80
      log_level: debug
      log_dir: /var/log/qxp-web
      # todo remove this
      templates_dir: /qxp-web/dist/templates
      # enable log to stdout
      enable_stdout: true

    home_server:
      server_port: 80
      log_level: debug
      log_dir: /var/log/qxp-web
      # todo remove this
      templates_dir: /qxp-web/dist/templates
      # enable log to stdout
      enable_stdout: true

    client_config:
      websocket_hostname: {{ .Values.websocket_hostname }}
      home_hostname: {{ .Values.home_hostname }}
      portal_hostname: {{ .Values.portal_hostname }}
      docs_hostname: docs.clouden.io