image:
  name: qxp-web-portal
  repo: docker.io/quanxiang
  tag: v1.1.2
namespace: ""
domain: example.com
mongo_host: ""
args:
  enabled: true
  endpoint: example.com:31198
  ip: xx.xx.xx.xx
kafka:
  value: kafka.lowcode.svc.cluster.local:9092
redis:
  host: ""
  password: ""
imagePullSecrets: ""
service:
  type: ClusterIP
  port: 80
  rpcPort: 0
nameOverride: ""
fullnameOverride: ""
websocket_hostname: ws.example.com
home_hostname: home.example.com
portal_hostname: portal.example.com
vendor:
  protocol: http
  hostname: vendors.example.com
  port: 80
serviceAccount:
  name: ""
podSecurityContext: {}
securityContext: {}
config:
  jwtKey: ""
  mysql:
    db: ""
    host: mysql.lowcode.svc.cluster.local:3306
    user: root
    password: qxp1234
    log: true
  redis:
    addrs:
    - example-distributedrediscluster-0.lowcode.svc.cluster.local:6379
    - example-distributedrediscluster-1.lowcode.svc.cluster.local:6379
    - example-distributedrediscluster-2.lowcode.svc.cluster.local:6379
    username: ""
    password: qxp1234
  elastic:
    log: true
    host:
    - http://elasticsearch-master.lowcode.svc.cluster.local:9200
  kafka:
    broker:
    - kafka.lowcode.svc.cluster.local:9092
    - ""
    - ""
  mongo:
    hosts:
    - mongodb.lowcode.svc.cluster.local:27017
    - ""
    - ""
    direct: false
    credential:
      authMechanism: SCRAM-SHA-1
      authSource: admin
      username: root
      password: qxp1234
      passwordSet: false
  etcd:
    enabled: false
    addrs:
    - etcd-cluster.lowcode.svc.cluster.local:2379
    username: null
    password: ""
  storage:
    option: minio
    urlExpire: 600
    partExpire: 604800
    launch: false
    storages:
    - name: minio
      protocol: http
      domain: home.qxp.com
      accessKey: Minio
      secretKey: Minio123456
      location: us-east-1
      bucketName: default
  email:
    emails: []
ingress:
  enabled: true
  hosts:
  - host: portal.example.com
    paths:
    - fullName: qxp-web-portal
      path: /
      svcPort: 80
    - fullName: qxp-web-nginx
      path: /dist
      svcPort: 80
app:
  kubernetes:
    io:
      name: fronted
