kind: Service
apiVersion: v1
metadata:
  name: transaction
  namespace: {{ .Values.namespace }}
  labels:
    app: transaction
    app.kubernetes.io/name: {{ .Values.app.kubernetes.io.name }}
    app.kubernetes.io/version: v1
    version: v1
  annotations:
    kubesphere.io/serviceType: statelessservice
    servicemesh.kubesphere.io/enabled: 'true'
spec:
  ports:
    - name: http-web
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: transaction
    app.kubernetes.io/version: v1
    app.kubernetes.io/name: {{ .Values.app.kubernetes.io.name }}
  type: {{ .Values.service.type }}
  sessionAffinity: None
